<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="0">

  <testsuite name="beforeWithClient"
    errors="1" failures="0" hostname="" id="" package="beforeWithClient" skipped="0"
    tests="0" time="0.000" timestamp="Mon, 24 Jul 2017 05:58:49 GMT">
  

  
    <system-err>
      Error: Provided error beforeWithClient
    at F.&lt;anonymous&gt; (/Users/Sneha/Documents/nightwatch-0.9.16/test/asynchookstests/async-provide-error/beforeWithClient.js:10:12)
    at F.Perform.command (/Users/Sneha/Documents/nightwatch-0.9.16/lib/api/client-commands/perform.js:58:14)
    at Object.commandFn (/Users/Sneha/Documents/nightwatch-0.9.16/lib/core/api.js:287:24)
    at AsyncTree.runCommand (/Users/Sneha/Documents/nightwatch-0.9.16/lib/core/queue.js:154:30)
    at AsyncTree.runChildNode (/Users/Sneha/Documents/nightwatch-0.9.16/lib/core/queue.js:114:8)
    at AsyncTree.walkDown (/Users/Sneha/Documents/nightwatch-0.9.16/lib/core/queue.js:80:10)
    at AsyncTree.traverse (/Users/Sneha/Documents/nightwatch-0.9.16/lib/core/queue.js:73:8)
    at Object.queueRunner [as run] (/Users/Sneha/Documents/nightwatch-0.9.16/lib/core/queue.js:216:18)
    at Nightwatch.start (/Users/Sneha/Documents/nightwatch-0.9.16/lib/index.js:206:14)
    at Object.onceWrapper (events.js:291:19)
    at emitThree (events.js:121:20)
    at Nightwatch.emit (events.js:195:7)
    at HttpRequest.&lt;anonymous&gt; (/Users/Sneha/Documents/nightwatch-0.9.16/lib/index.js:481:12)
    at emitThree (events.js:116:13)
    at HttpRequest.emit (events.js:195:7)
    at IncomingMessage.&lt;anonymous&gt; (/Users/Sneha/Documents/nightwatch-0.9.16/lib/http/request.js:166:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    </system-err>
  

  
  </testsuite>
</testsuites>
